url: http://tylerray.github.io
baseurl: http://tylerray.github.io
timezone:
destination: _build
exclude: ['README.md', '.sass-cache']
include: [.htaccess]
markdown: redcarpet
highlighter: pygments
permalink: /blog/:year/:month/:day/:title/
sass:
  style: compressed
gems:
    - jekyll-sitemap
